---
header-includes:
   - \usepackage{bbm}
   - \usepackage{mathtools}
   - \usepackage{amsmath}
---


# Trans-Women in Sports

A complication arises, if we accept the Butlerian separation of gender from sex: Should biological males identifying as women compete in women's sports? Having gone through male puberty, trans women have an advantage over females in many sports. But there are also large genetic differences within sexes, creating unfair advantages for some individuals. I demonstrate how small differences in athletic prowess between an average male and female can lead to large differences between the male and female pro athletes.


### Introduction

Women's sports is a protected class set up to increase the representation and possibilities of female athletes. Trans-women have gone through puberty as males, with higher testosterone accumulating muscle mass, more dense joints, increasing competitiveness and pain tolerance among else. In many sports this gives an advantage over females. But does these differences matter? Males and females are more similar than different, and there are also large genetic differences within sexes, which creates an uneven playing field to begin with. Trans-women also have a dis-advantage competing against males due to their estrogen therapy.

Despite a large overlap in athletic prowess between the populations, even small differences in population averages translate to large differences at the extremes. The consequence of this statistical property is that the sex-differences between professional male and female athletes are large even if an average male and female are somewhat alike.



### Differences exaggerate at the extreme

Consider a case, where an individual's athletic prowess is drawn from sex-specific probability distributions, $X_{if} \sim \mathcal{N}(\mu_f, \sigma_f^2)$ and $X_{im} \sim \mathcal N(\mu_m, \sigma_m^2)$, where $i\in\{1,\dots,N\}$, $N_f=N_m$, $\mu_m>\mu_f$ and $\sigma_m>\sigma_f$, and $\{f,m\}$ denote for female and male sex, respectively. An athlete is someone with an athletic prowess greater than 98 \% of the population. The male and female cutoffs for athletes are depicted by dashed lines in Figure below.


```{r simulation, echo=FALSE, show=TRUE}
# Generate population
N = 100000
male <- rnorm(N, 7.5, 2)
female <- rnorm(N, 6.5, 1.5)

# Find athletes
cutoff_ath <- 0.98
male_cutoff <- male[order(male)[round(cutoff_ath*length(male))]]
female_cutoff <- female[order(female)[round(cutoff_ath*length(female))]]

athlete_males <- male[which(male>male_cutoff)]
athlete_females <- female[which(female>female_cutoff)]


# Visualize
par(mfrow=c(1,2), mar=c(5,2,2,2))
bblue <- rgb(89,202,243,max=255,alpha=150,names="blue50")
rred <- rgb(200,0,0,max=255,alpha=150,names="red50")

# Whole
hist(female, xlim=range(male,female), breaks=30, col=rred,
     xlab="Athletic prowess", ylab=c(""), cex.main=1.4, main="Whole population")
hist(male, xlim=range(male,female), breaks=30, col=bblue, add=TRUE)
abline(v=male_cutoff, col=bblue, lty=2, lwd=3)
abline(v=female_cutoff, col=rred, lty=2, lwd=3)

# Athletes
hist(athlete_females, xlim=range(athlete_males,athlete_females), breaks=20, col=rred,
     xlab="Athletic prowess", ylab=c(""), cex.main=1.4, main="Athletes (>98%)")
hist(athlete_males, xlim=range(male,female), breaks=30, col=bblue, add=TRUE)
legend("topright", legend=c("female", "male", ">98% f", ">98% m"),
       col=c(rred, bblue), lty=c(1,1,2,2), lwd=1.3, cex=1.1, bty="n")

```

On the left a large overlap can be seen in the athletic ability between the male and female populations, but the gap widens on the right when only the top 2\% of males and females are compared.

Even small differences in expected values and variances between two largely overlapping populations (males and females) can translate into large differences at the extremes. There are many females who are stronger than many males, but for example at the elite level of powerlifting there are virtually no females who are stronger than any of the males.

### What to do?

Including trans-women in womens sports would be unfair to women. One option would be to re-brand women's sports as female sports, but then trans-men (females) who are on testosterone replacement therapy would have an unfair pharmacological advantage. Creating a separate class for trans-sports would lead to very small participation numbers. We could maintain a protected class for female women and create an open class for everyone else. However, this would be unfair to both trans women and -men who either have medically lowered testosterone or lack the male puberty. attention has mostly been on trans-women, who can potentially thrive  in womens sports, but rans-men athletes have it worse as they will not have a competitive advantage in any of the leagues.

One way to approach the problem would be to abolish the gendeder leagues and come up with new metrics based on bone density, lean muscle mass, lung capacity or other relevant markers to craft fair and competitive leagues for different sports.
